/* Generated by @deepseek-ai/dsh-typert-generator from the Host FaceModel — do not edit. */
import type {
  RemoteResult,
  TypertRemoteContribution,
} from '@deepseek-ai/dsh-typert-protocol'
import type { KersorActiveLaunch, KersorTaskId, KersorTaskRef } from '@deepseek-ai/dsh-kersor/types'

declare module '@deepseek-ai/dsh-typert-protocol' {
  interface TypertRemoteNamespace$6b6572736f72 {
    listActive: () => Promise<RemoteResult<KersorActiveLaunch[]>>
    listTasks: () => Promise<RemoteResult<KersorTaskRef[]>>
    start: (taskId: KersorTaskId) => Promise<RemoteResult<KersorActiveLaunch>>
    stop: (runDir: string) => Promise<RemoteResult<boolean>>
  }
  interface TypertRemoteMap {
    'kersor/listActive': () => Promise<RemoteResult<KersorActiveLaunch[]>>
    'kersor/listTasks': () => Promise<RemoteResult<KersorTaskRef[]>>
    'kersor/start': (taskId: KersorTaskId) => Promise<RemoteResult<KersorActiveLaunch>>
    'kersor/stop': (runDir: string) => Promise<RemoteResult<boolean>>
  }
  interface TypertRemoteNamespaceMap {
    'kersor': TypertRemoteNamespace$6b6572736f72
  }
}

export declare const TYPERT_REMOTE: TypertRemoteContribution
export default TYPERT_REMOTE
//# sourceMappingURL=typert.remote-client.d.ts.map
