/* Generated by @deepseek-ai/dsh-typert-generator from FaceModel — do not edit. */
import { z } from 'zod'

const _deepseek_ai_dsh_kersor_kersor_listActive_result$schema = z.array(z.object({
  'taskId': z.intersection(z.string(), z.unknown()).readonly(),
  'runId': z.intersection(z.string(), z.unknown()).readonly(),
  'runDir': z.string().readonly(),
  'startedTs': z.string().readonly(),
  'pid': z.number().readonly(),
}))
const _deepseek_ai_dsh_kersor_kersor_listTasks_result$schema = z.array(z.object({
  'id': z.intersection(z.string(), z.unknown()).readonly(),
  'label': z.string().readonly(),
}))
const _deepseek_ai_dsh_kersor_kersor_start_parameter_0$schema = z.intersection(z.string(), z.unknown())
const _deepseek_ai_dsh_kersor_kersor_start_result$schema = z.object({
  'taskId': z.intersection(z.string(), z.unknown()).readonly(),
  'runId': z.intersection(z.string(), z.unknown()).readonly(),
  'runDir': z.string().readonly(),
  'startedTs': z.string().readonly(),
  'pid': z.number().readonly(),
})
const _deepseek_ai_dsh_kersor_kersor_stop_parameter_0$schema = z.string()
const _deepseek_ai_dsh_kersor_kersor_stop_result$schema = z.boolean()

export const TYPERT = {
  package: '@deepseek-ai/dsh-kersor',
  face: 'host',
  schemas: [
  ],
  invocations: [
    {
      id: '@deepseek-ai/dsh-kersor#kersor/listActive',
      service: 'kersor',
      namespace: 'kersor',
      method: 'listActive',
      invocation: { kind: 'direct' },
      parameters: [
      ],
      result: {
        mode: 'strict',
        typeSymbol: '@deepseek-ai/dsh-kersor#kersor/listActive:result',
        schema: _deepseek_ai_dsh_kersor_kersor_listActive_result$schema,
      },
      sourceLocation: {"file":"packages/extensions/kersor/src/service.ts","line":169,"column":3},
    },
    {
      id: '@deepseek-ai/dsh-kersor#kersor/listTasks',
      service: 'kersor',
      namespace: 'kersor',
      method: 'listTasks',
      invocation: { kind: 'direct' },
      parameters: [
      ],
      result: {
        mode: 'strict',
        typeSymbol: '@deepseek-ai/dsh-kersor#kersor/listTasks:result',
        schema: _deepseek_ai_dsh_kersor_kersor_listTasks_result$schema,
      },
      sourceLocation: {"file":"packages/extensions/kersor/src/service.ts","line":160,"column":3},
    },
    {
      id: '@deepseek-ai/dsh-kersor#kersor/start',
      service: 'kersor',
      namespace: 'kersor',
      method: 'start',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'taskId',
          wire: 'taskId',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@deepseek-ai/dsh-kersor/types#KersorTaskId',
            schema: _deepseek_ai_dsh_kersor_kersor_start_parameter_0$schema,
          },
        },
      ],
      result: {
        mode: 'strict',
        typeSymbol: '@deepseek-ai/dsh-kersor/types#KersorActiveLaunch',
        schema: _deepseek_ai_dsh_kersor_kersor_start_result$schema,
      },
      sourceLocation: {"file":"packages/extensions/kersor/src/service.ts","line":181,"column":9},
    },
    {
      id: '@deepseek-ai/dsh-kersor#kersor/stop',
      service: 'kersor',
      namespace: 'kersor',
      method: 'stop',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'runDir',
          wire: 'runDir',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@deepseek-ai/dsh-kersor#kersor/stop:runDir',
            schema: _deepseek_ai_dsh_kersor_kersor_stop_parameter_0$schema,
          },
        },
      ],
      result: {
        mode: 'strict',
        typeSymbol: '@deepseek-ai/dsh-kersor#kersor/stop:result',
        schema: _deepseek_ai_dsh_kersor_kersor_stop_result$schema,
      },
      sourceLocation: {"file":"packages/extensions/kersor/src/service.ts","line":234,"column":9},
    },
  ],
  model: {
    "services": [
      {
        "description": "Host-side launcher over registered KerSor autonomous Missions.",
        "summary": "Host-side launcher over registered KerSor autonomous Missions.",
        "tags": [],
        "jsDoc": "/** Host-side launcher over registered KerSor autonomous Missions. */",
        "key": "kersor",
        "exportName": "KersorService",
        "members": [
          {
            "kind": "method",
            "name": "[Service.init]",
            "signature": "async* [Service.init](): AsyncGenerator<() => Promise<void>, void, void>",
            "summary": "Validate self-contained configuration and quiesce every owned launch on disposal.",
            "jsDoc": "/** Validate self-contained configuration and quiesce every owned launch on disposal. */"
          },
          {
            "kind": "method",
            "name": "listTasks",
            "signature": "@Remote('listTasks') listTasks(): KersorTaskRef[]",
            "summary": "Return the configured Mission registry without exposing host paths.",
            "jsDoc": "/**\n * Return the configured Mission registry without exposing host paths.\n * @returns tasks in configuration order.\n */"
          },
          {
            "kind": "method",
            "name": "listActive",
            "signature": "@Remote('listActive') listActive(): KersorActiveLaunch[]",
            "summary": "Return launcher processes dsh still owns.",
            "jsDoc": "/**\n * Return launcher processes dsh still owns.\n * @returns active launch receipts in start order.\n */"
          },
          {
            "kind": "method",
            "name": "start",
            "signature": "@Remote('start') async start(taskId: KersorTaskId): Promise<KersorActiveLaunch>",
            "summary": "Start one configured Mission and return after the process tree is owned.",
            "jsDoc": "/**\n * Start one configured Mission and return after the process tree is owned.\n * Workflow completion is observed through `dsh-kersor-viewer`, not this receipt.\n * @param taskId - configured task identity from {@link listTasks}.\n * @returns active launcher receipt, including the deterministic run directory.\n * @throws when config, credentials, Mission routing, or process spawn is invalid.\n */"
          },
          {
            "kind": "method",
            "name": "stop",
            "signature": "@Remote('stop') async stop(runDir: string): Promise<boolean>",
            "summary": "Terminate one process tree and wait for quiescence.",
            "jsDoc": "/**\n * Terminate one process tree and wait for quiescence.\n * @param runDir - exact run directory returned by {@link start}.\n * @returns false when this service does not own that run.\n */"
          }
        ],
        "types": [
          {
            "name": "Branded",
            "declaration": "export type Branded<B extends string> = string & { readonly [BRAND]: B; };"
          },
          {
            "name": "KersorActiveLaunch",
            "declaration": "export interface KersorActiveLaunch {\n    readonly taskId: KersorTaskId;\n    readonly runId: KersorRunId;\n    readonly runDir: string;\n    readonly startedTs: string;\n    readonly pid: number;\n}"
          },
          {
            "name": "KersorRunId",
            "declaration": "export type KersorRunId = Branded<'KersorRunId'>;"
          },
          {
            "name": "KersorTaskId",
            "declaration": "export type KersorTaskId = Branded<'KersorTaskId'>;"
          },
          {
            "name": "KersorTaskRef",
            "declaration": "export interface KersorTaskRef {\n    readonly id: KersorTaskId;\n    readonly label: string;\n}"
          }
        ]
      }
    ],
    "events": [
      {
        "description": "Current KerSor processes owned by the launcher.",
        "summary": "Current KerSor processes owned by the launcher.",
        "tags": [
          {
            "name": "param",
            "argument": "frame",
            "comment": "- complete replacement of the active-launch inventory.",
            "text": "@param frame - complete replacement of the active-launch inventory.\n     *"
          },
          {
            "name": "mode",
            "comment": "emit",
            "text": "@mode emit"
          }
        ],
        "jsDoc": "/**\n * Current KerSor processes owned by the launcher.\n * @param frame - complete replacement of the active-launch inventory.\n * @mode emit\n */",
        "name": "kersor/active",
        "mode": "emit",
        "signature": "'kersor/active'(frame: KersorActiveFrame): void"
      }
    ],
    "objects": []
  },
}
