/* Generated by @deepseek-ai/dsh-typert-generator from the Host FaceModel — do not edit. */
import type {
  RemoteResult,
  TypertRemoteContribution,
} from '@deepseek-ai/dsh-typert-protocol'
import type { KersorClassicSnapshot, KersorRunRef, KersorRunView } from '@deepseek-ai/dsh-kersor-viewer/types'

declare module '@deepseek-ai/dsh-typert-protocol' {
  interface TypertRemoteNamespace$6b6572736f72566965776572 {
    listClassicSessions: () => Promise<RemoteResult<KersorClassicSnapshot>>
    listRuns: () => Promise<RemoteResult<KersorRunRef[]>>
    runBacklog: (runDir: string) => Promise<RemoteResult<KersorRunView | undefined>>
  }
  interface TypertRemoteMap {
    'kersorViewer/listClassicSessions': () => Promise<RemoteResult<KersorClassicSnapshot>>
    'kersorViewer/listRuns': () => Promise<RemoteResult<KersorRunRef[]>>
    'kersorViewer/runBacklog': (runDir: string) => Promise<RemoteResult<KersorRunView | undefined>>
  }
  interface TypertRemoteNamespaceMap {
    'kersorViewer': TypertRemoteNamespace$6b6572736f72566965776572
  }
}

export declare const TYPERT_REMOTE: TypertRemoteContribution
export default TYPERT_REMOTE
//# sourceMappingURL=typert.remote-client.d.ts.map
