/* Generated by @deepseek-ai/dsh-typert-generator from FaceModel — do not edit. */
import { z } from 'zod'

const _deepseek_ai_dsh_kersor_viewer_kersorViewer_listRuns_result$schema = z.array(z.object({
  'runId': z.string().readonly(),
  'runDir': z.string().readonly(),
  'sessionDir': z.string().readonly(),
  'root': z.string().readonly(),
  'discovery': z.union([z.literal("failed"), z.literal("active"), z.literal("completed")]).readonly(),
}))
const _deepseek_ai_dsh_kersor_viewer_kersorViewer_runBacklog_parameter_0$schema = z.string()
const _deepseek_ai_dsh_kersor_viewer_kersorViewer_runBacklog_result$schema = z.union([z.undefined(), z.object({
  'runId': z.string().readonly(),
  'runDir': z.string().readonly(),
  'sessionDir': z.string().readonly(),
  'status': z.union([z.literal("running"), z.literal("failed"), z.literal("completed"), z.literal("unknown")]),
  'startedTs': z.union([z.undefined(), z.string()]).optional(),
  'endedTs': z.union([z.undefined(), z.string()]).optional(),
  'currentPhase': z.string(),
  'phases': z.array(z.object({
  'title': z.string().readonly(),
  'index': z.number().readonly(),
  'status': z.union([z.literal("running"), z.literal("failed"), z.literal("completed")]),
  'calls': z.array(z.object({
  'seq': z.number().readonly(),
  'callId': z.string().readonly(),
  'label': z.string().readonly(),
  'kind': z.union([z.literal("agent"), z.literal("evaluation")]).readonly(),
  'status': z.union([z.literal("running"), z.literal("failed"), z.literal("completed"), z.literal("queued")]),
  'startedTs': z.union([z.undefined(), z.string()]).optional(),
  'endedTs': z.union([z.undefined(), z.string()]).optional(),
  'tokens': z.union([z.undefined(), z.number()]).optional(),
  'rolledBack': z.union([z.undefined(), z.literal(false), z.literal(true)]).optional(),
  'error': z.union([z.undefined(), z.string()]).optional(),
})).readonly(),
})),
  'totals': z.object({
  'calls': z.number(),
  'completed': z.number(),
  'failed': z.number(),
  'tokens': z.number(),
}),
  'error': z.union([z.undefined(), z.string()]).optional(),
})])

export const TYPERT = {
  package: '@deepseek-ai/dsh-kersor-viewer',
  face: 'host',
  schemas: [
  ],
  invocations: [
    {
      id: '@deepseek-ai/dsh-kersor-viewer#kersorViewer/listRuns',
      service: 'kersorViewer',
      namespace: 'kersorViewer',
      method: 'listRuns',
      invocation: { kind: 'direct' },
      parameters: [
      ],
      result: {
        mode: 'strict',
        typeSymbol: '@deepseek-ai/dsh-kersor-viewer#kersorViewer/listRuns:result',
        schema: _deepseek_ai_dsh_kersor_viewer_kersorViewer_listRuns_result$schema,
      },
      sourceLocation: {"file":"packages/extensions/kersor-viewer/src/service.ts","line":103,"column":3},
    },
    {
      id: '@deepseek-ai/dsh-kersor-viewer#kersorViewer/runBacklog',
      service: 'kersorViewer',
      namespace: 'kersorViewer',
      method: 'runBacklog',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'runDir',
          wire: 'runDir',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@deepseek-ai/dsh-kersor-viewer#kersorViewer/runBacklog:runDir',
            schema: _deepseek_ai_dsh_kersor_viewer_kersorViewer_runBacklog_parameter_0$schema,
          },
        },
      ],
      result: {
        mode: 'strict',
        typeSymbol: '@deepseek-ai/dsh-kersor-viewer#kersorViewer/runBacklog:result',
        schema: _deepseek_ai_dsh_kersor_viewer_kersorViewer_runBacklog_result$schema,
      },
      sourceLocation: {"file":"packages/extensions/kersor-viewer/src/service.ts","line":110,"column":3},
    },
  ],
  model: {
    "services": [],
    "events": [
      {
        "description": "One viewer update: a replaced run inventory or one run's folded view.",
        "summary": "One viewer update: a replaced run inventory or one run's folded view.",
        "tags": [
          {
            "name": "param",
            "argument": "frame",
            "comment": "- inventory list or folded run view model.",
            "text": "@param frame - inventory list or folded run view model.\n     *"
          },
          {
            "name": "mode",
            "comment": "emit",
            "text": "@mode emit"
          }
        ],
        "jsDoc": "/**\n * One viewer update: a replaced run inventory or one run's folded view.\n * @param frame - inventory list or folded run view model.\n * @mode emit\n */",
        "name": "kersor/event",
        "mode": "emit",
        "signature": "'kersor/event'(frame: KersorViewerFrame): void"
      }
    ],
    "objects": []
  },
}
