/* Generated by @deepseek-ai/dsh-typert-generator from the Host FaceModel — do not edit. */
import type {
  RemoteResult,
  TypertRemoteContribution,
} from '@deepseek-ai/dsh-typert-protocol'
import type { KersorClassicSessionDetail, KersorRunView, KersorViewerSnapshot } from '@deepseek-ai/dsh-kersor-viewer/types'

declare module '@deepseek-ai/dsh-typert-protocol' {
  interface TypertRemoteNamespace$6b6572736f72566965776572 {
    classicSessionDetail: (sessionDir: string) => Promise<RemoteResult<KersorClassicSessionDetail | undefined>>
    runBacklog: (runDir: string) => Promise<RemoteResult<KersorRunView | undefined>>
    snapshot: () => Promise<RemoteResult<KersorViewerSnapshot>>
  }
  interface TypertRemoteMap {
    'kersorViewer/classicSessionDetail': (sessionDir: string) => Promise<RemoteResult<KersorClassicSessionDetail | undefined>>
    'kersorViewer/runBacklog': (runDir: string) => Promise<RemoteResult<KersorRunView | undefined>>
    'kersorViewer/snapshot': () => Promise<RemoteResult<KersorViewerSnapshot>>
  }
  interface TypertRemoteNamespaceMap {
    'kersorViewer': TypertRemoteNamespace$6b6572736f72566965776572
  }
}

export declare const TYPERT_REMOTE: TypertRemoteContribution
export default TYPERT_REMOTE
//# sourceMappingURL=typert.remote-client.d.ts.map
