/* Generated by @deepseek-ai/dsh-typert-generator from FaceModel — do not edit. */
import { z } from 'zod'

const _deepseek_ai_dsh_kersor_viewer_kersorViewer_classicSessionDetail_parameter_0$schema = z.string()
const _deepseek_ai_dsh_kersor_viewer_kersorViewer_classicSessionDetail_result$schema = z.union([z.undefined(), z.object({
  'session_id': z.string().readonly(),
  'session_dir': z.string().readonly(),
  'current_round': z.number().readonly(),
  'steps': z.array(z.object({
  'id': z.union([z.literal("setup"), z.literal("baseline"), z.literal("profile"), z.literal("selection"), z.literal("authoring"), z.literal("validation"), z.literal("dispatch"), z.literal("measurement"), z.literal("decision")]).readonly(),
  'status': z.union([z.literal("failed"), z.literal("pending"), z.literal("active"), z.literal("completed")]).readonly(),
})).readonly(),
  'selection': z.object({
  'status': z.union([z.literal("pending"), z.literal("stalled"), z.literal("selected")]).readonly(),
  'workflow': z.string().readonly().optional(),
  'reason': z.string().readonly().optional(),
  'rejectedCount': z.number().readonly(),
}).readonly(),
  'authoring': z.object({
  'status': z.union([z.literal("rejected"), z.literal("not_started"), z.literal("in_progress"), z.literal("sealed"), z.literal("saved")]).readonly(),
  'files': z.array(z.object({
  'name': z.string().readonly(),
  'sha256': z.string().readonly(),
  'bytes': z.number().readonly(),
})).readonly(),
  'design': z.object({
  'name': z.string().readonly().optional(),
  'technique': z.string().readonly().optional(),
  'methodCategory': z.string().readonly().optional(),
  'topology': z.string().readonly().optional(),
  'requiredArgs': z.array(z.string()).readonly(),
  'languages': z.array(z.string()).readonly(),
  'backends': z.array(z.string()).readonly(),
  'integrationPatterns': z.array(z.string()).readonly(),
  'rationale': z.string().readonly(),
  'source': z.string().readonly(),
}).readonly().optional(),
  'omittedReason': z.union([z.literal("too_large"), z.literal("invalid"), z.literal("hash_mismatch")]).readonly().optional(),
}).readonly(),
  'validation': z.object({
  'status': z.union([z.literal("failed"), z.literal("pending"), z.literal("passed")]).readonly(),
  'checks': z.array(z.object({
  'name': z.string().readonly(),
  'passed': z.boolean().readonly(),
})).readonly(),
}).readonly(),
  'dispatch': z.object({
  'status': z.union([z.literal("running"), z.literal("failed"), z.literal("pending"), z.literal("completed"), z.literal("preparing")]).readonly(),
  'runDir': z.string().readonly().optional(),
  'runtimeStatus': z.string().readonly().optional(),
}).readonly(),
})])
const _deepseek_ai_dsh_kersor_viewer_kersorViewer_runBacklog_parameter_0$schema = z.string()
const _deepseek_ai_dsh_kersor_viewer_kersorViewer_runBacklog_result$schema = z.union([z.undefined(), z.object({
  'runId': z.string().readonly(),
  'runDir': z.string().readonly(),
  'sessionDir': z.string().readonly(),
  'status': z.union([z.literal("running"), z.literal("failed"), z.literal("completed"), z.literal("unknown")]),
  'startedTs': z.union([z.undefined(), z.string()]).optional(),
  'endedTs': z.union([z.undefined(), z.string()]).optional(),
  'currentPhase': z.string(),
  'phases': z.array(z.object({
  'title': z.string().readonly(),
  'index': z.number().readonly(),
  'status': z.union([z.literal("running"), z.literal("failed"), z.literal("completed")]),
  'calls': z.array(z.object({
  'seq': z.number().readonly(),
  'callId': z.string().readonly(),
  'label': z.string().readonly(),
  'kind': z.union([z.literal("agent"), z.literal("evaluation")]).readonly(),
  'status': z.union([z.literal("running"), z.literal("failed"), z.literal("completed"), z.literal("queued")]),
  'startedTs': z.union([z.undefined(), z.string()]).optional(),
  'endedTs': z.union([z.undefined(), z.string()]).optional(),
  'tokens': z.union([z.undefined(), z.number()]).optional(),
  'rolledBack': z.union([z.undefined(), z.literal(false), z.literal(true)]).optional(),
  'error': z.union([z.undefined(), z.string()]).optional(),
})).readonly(),
})),
  'totals': z.object({
  'calls': z.number(),
  'completed': z.number(),
  'failed': z.number(),
  'tokens': z.number(),
}),
  'error': z.union([z.undefined(), z.string()]).optional(),
})])
const _deepseek_ai_dsh_kersor_viewer_kersorViewer_snapshot_result$schema = z.object({
  'asOf': z.string().readonly(),
  'runs': z.array(z.object({
  'runId': z.string().readonly(),
  'runDir': z.string().readonly(),
  'sessionDir': z.string().readonly(),
  'root': z.string().readonly(),
  'discovery': z.union([z.literal("failed"), z.literal("active"), z.literal("completed")]).readonly(),
})).readonly(),
  'classic': z.object({
  'sessions': z.array(z.object({
  'session_id': z.string().readonly(),
  'session_dir': z.string().readonly(),
  'storage_kind': z.union([z.literal("v2"), z.literal("legacy")]).readonly(),
  'phase': z.union([z.literal(null), z.string()]).readonly().optional(),
  'lifecycle': z.union([z.literal("cancelled"), z.literal("active"), z.literal("completed"), z.literal("stalled")]).readonly(),
  'status': z.union([z.literal("terminal-complete"), z.literal("terminal-stalled"), z.literal("terminal-cancelled"), z.literal("resumable"), z.literal("in-progress"), z.literal("pre-round-1")]).readonly(),
  'health': z.union([z.literal("active"), z.literal("stale"), z.literal("needs_resume"), z.literal("terminal"), z.literal("unknown")]).readonly(),
  'started_at': z.union([z.literal(null), z.string()]).readonly().optional(),
  'last_activity_at': z.union([z.literal(null), z.string()]).readonly().optional(),
  'current_round': z.union([z.literal(null), z.number()]).readonly().optional(),
  'max_workflows': z.union([z.literal(null), z.number()]).readonly().optional(),
  'target_speedup': z.union([z.literal(null), z.number()]).readonly().optional(),
  'target_met': z.union([z.literal(null), z.literal(false), z.literal(true)]).readonly().optional(),
  'mode': z.union([z.literal(null), z.string()]).readonly().optional(),
  'backend': z.union([z.literal(null), z.string()]).readonly().optional(),
  'kernel_language': z.union([z.literal(null), z.string()]).readonly().optional(),
  'integration_pattern': z.union([z.literal(null), z.string()]).readonly().optional(),
  'allow_workflow_authoring': z.union([z.literal(null), z.literal(false), z.literal(true)]).readonly().optional(),
  'workflow_authoring_budget': z.union([z.literal(null), z.number()]).readonly().optional(),
  'kernel_name': z.union([z.literal(null), z.string()]).readonly().optional(),
  'workflow': z.union([z.literal(null), z.string()]).readonly().optional(),
  'selection_status': z.union([z.literal(null), z.literal("pending"), z.literal("stalled"), z.literal("selected")]).readonly().optional(),
  'decision': z.union([z.literal(null), z.string()]).readonly().optional(),
  'fit_confidence': z.union([z.literal(null), z.string()]).readonly().optional(),
  'baseline_witness': z.union([z.literal(null), z.literal("pending"), z.literal("pass"), z.literal("fail"), z.literal("not_required")]).readonly().optional(),
  'baseline_next_action': z.union([z.literal(null), z.literal("init"), z.literal("record_verify"), z.literal("new_session")]).readonly().optional(),
  'baseline_reason': z.union([z.literal(null), z.string()]).readonly().optional(),
  'dsh_compatibility': z.union([z.literal(null), z.literal("pending"), z.literal("pass"), z.literal("fail"), z.literal("not_required")]).readonly().optional(),
  'candidate_ownership': z.union([z.literal(null), z.literal("pending"), z.literal("pass"), z.literal("fail"), z.literal("not_required")]).readonly().optional(),
  'fresh_session': z.union([z.literal(null), z.literal("pending"), z.literal("pass"), z.literal("fail"), z.literal("not_required")]).readonly().optional(),
  'best_speedup': z.union([z.literal(null), z.number()]).readonly().optional(),
  'warningCount': z.number().readonly(),
})).readonly(),
  'source': z.object({
  'state': z.union([z.literal("failed"), z.literal("disabled"), z.literal("not_installed"), z.literal("healthy"), z.literal("degraded")]).readonly(),
  'lastIssue': z.object({
  'stage': z.union([z.literal("checkout_pointer"), z.literal("root_scan"), z.literal("session_inspect"), z.literal("runs_scan"), z.literal("summary_read"), z.literal("backfill_read"), z.literal("event_parse"), z.literal("event_fold"), z.literal("tailer_watch"), z.literal("tailer_read"), z.literal("classic_bridge")]).readonly(),
  'code': z.union([z.literal("not_found"), z.literal("permission_denied"), z.literal("invalid_json"), z.literal("invalid_payload"), z.literal("watch_unavailable"), z.literal("process_unavailable"), z.literal("timeout"), z.literal("io_error"), z.literal("unexpected")]).readonly(),
  'severity': z.union([z.literal("error"), z.literal("warning")]).readonly(),
  'occurrences': z.number().readonly(),
  'lastSeenAt': z.string().readonly(),
}).readonly().optional(),
}).readonly(),
}).readonly(),
  'diagnostics': z.object({
  'scan': z.object({
  'state': z.union([z.literal("running"), z.literal("failed"), z.literal("healthy"), z.literal("degraded"), z.literal("never")]).readonly(),
  'startedAt': z.string().readonly().optional(),
  'completedAt': z.string().readonly().optional(),
  'lastSuccessfulAt': z.string().readonly().optional(),
  'roots': z.array(z.object({
  'root': z.string().readonly(),
  'origin': z.union([z.literal("configured"), z.literal("default"), z.literal("checkout"), z.literal("workspace")]).readonly(),
  'state': z.union([z.literal("failed"), z.literal("absent"), z.literal("healthy"), z.literal("degraded")]).readonly(),
  'sessionsExamined': z.number().readonly(),
  'sessionsAccepted': z.number().readonly(),
  'runsFound': z.number().readonly(),
  'lastIssue': z.object({
  'stage': z.union([z.literal("checkout_pointer"), z.literal("root_scan"), z.literal("session_inspect"), z.literal("runs_scan"), z.literal("summary_read"), z.literal("backfill_read"), z.literal("event_parse"), z.literal("event_fold"), z.literal("tailer_watch"), z.literal("tailer_read"), z.literal("classic_bridge")]).readonly(),
  'code': z.union([z.literal("not_found"), z.literal("permission_denied"), z.literal("invalid_json"), z.literal("invalid_payload"), z.literal("watch_unavailable"), z.literal("process_unavailable"), z.literal("timeout"), z.literal("io_error"), z.literal("unexpected")]).readonly(),
  'severity': z.union([z.literal("error"), z.literal("warning")]).readonly(),
  'occurrences': z.number().readonly(),
  'lastSeenAt': z.string().readonly(),
}).readonly().optional(),
})).readonly(),
  'lastIssue': z.object({
  'stage': z.union([z.literal("checkout_pointer"), z.literal("root_scan"), z.literal("session_inspect"), z.literal("runs_scan"), z.literal("summary_read"), z.literal("backfill_read"), z.literal("event_parse"), z.literal("event_fold"), z.literal("tailer_watch"), z.literal("tailer_read"), z.literal("classic_bridge")]).readonly(),
  'code': z.union([z.literal("not_found"), z.literal("permission_denied"), z.literal("invalid_json"), z.literal("invalid_payload"), z.literal("watch_unavailable"), z.literal("process_unavailable"), z.literal("timeout"), z.literal("io_error"), z.literal("unexpected")]).readonly(),
  'severity': z.union([z.literal("error"), z.literal("warning")]).readonly(),
  'occurrences': z.number().readonly(),
  'lastSeenAt': z.string().readonly(),
}).readonly().optional(),
}).readonly(),
  'runs': z.array(z.object({
  'runDir': z.string().readonly(),
  'mode': z.union([z.literal("tail"), z.literal("backfill")]).readonly(),
  'state': z.union([z.literal("waiting"), z.literal("failed"), z.literal("complete"), z.literal("healthy"), z.literal("degraded")]).readonly(),
  'byteOffset': z.number().readonly(),
  'linesRead': z.number().readonly(),
  'linesRejected': z.number().readonly(),
  'lastReadAt': z.string().readonly().optional(),
  'lastIssue': z.object({
  'stage': z.union([z.literal("checkout_pointer"), z.literal("root_scan"), z.literal("session_inspect"), z.literal("runs_scan"), z.literal("summary_read"), z.literal("backfill_read"), z.literal("event_parse"), z.literal("event_fold"), z.literal("tailer_watch"), z.literal("tailer_read"), z.literal("classic_bridge")]).readonly(),
  'code': z.union([z.literal("not_found"), z.literal("permission_denied"), z.literal("invalid_json"), z.literal("invalid_payload"), z.literal("watch_unavailable"), z.literal("process_unavailable"), z.literal("timeout"), z.literal("io_error"), z.literal("unexpected")]).readonly(),
  'severity': z.union([z.literal("error"), z.literal("warning")]).readonly(),
  'occurrences': z.number().readonly(),
  'lastSeenAt': z.string().readonly(),
}).readonly().optional(),
})).readonly(),
}).readonly(),
})

export const TYPERT = {
  package: '@deepseek-ai/dsh-kersor-viewer',
  face: 'host',
  schemas: [
  ],
  invocations: [
    {
      id: '@deepseek-ai/dsh-kersor-viewer#kersorViewer/classicSessionDetail',
      service: 'kersorViewer',
      namespace: 'kersorViewer',
      method: 'classicSessionDetail',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'sessionDir',
          wire: 'sessionDir',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@deepseek-ai/dsh-kersor-viewer#kersorViewer/classicSessionDetail:sessionDir',
            schema: _deepseek_ai_dsh_kersor_viewer_kersorViewer_classicSessionDetail_parameter_0$schema,
          },
        },
      ],
      result: {
        mode: 'strict',
        typeSymbol: '@deepseek-ai/dsh-kersor-viewer#kersorViewer/classicSessionDetail:result',
        schema: _deepseek_ai_dsh_kersor_viewer_kersorViewer_classicSessionDetail_result$schema,
      },
      sourceLocation: {"file":"packages/extensions/kersor-viewer/src/service.ts","line":150,"column":9},
    },
    {
      id: '@deepseek-ai/dsh-kersor-viewer#kersorViewer/runBacklog',
      service: 'kersorViewer',
      namespace: 'kersorViewer',
      method: 'runBacklog',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'runDir',
          wire: 'runDir',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@deepseek-ai/dsh-kersor-viewer#kersorViewer/runBacklog:runDir',
            schema: _deepseek_ai_dsh_kersor_viewer_kersorViewer_runBacklog_parameter_0$schema,
          },
        },
      ],
      result: {
        mode: 'strict',
        typeSymbol: '@deepseek-ai/dsh-kersor-viewer#kersorViewer/runBacklog:result',
        schema: _deepseek_ai_dsh_kersor_viewer_kersorViewer_runBacklog_result$schema,
      },
      sourceLocation: {"file":"packages/extensions/kersor-viewer/src/service.ts","line":140,"column":3},
    },
    {
      id: '@deepseek-ai/dsh-kersor-viewer#kersorViewer/snapshot',
      service: 'kersorViewer',
      namespace: 'kersorViewer',
      method: 'snapshot',
      invocation: { kind: 'direct' },
      parameters: [
      ],
      result: {
        mode: 'strict',
        typeSymbol: '@deepseek-ai/dsh-kersor-viewer/types#KersorViewerSnapshot',
        schema: _deepseek_ai_dsh_kersor_viewer_kersorViewer_snapshot_result$schema,
      },
      sourceLocation: {"file":"packages/extensions/kersor-viewer/src/service.ts","line":124,"column":3},
    },
  ],
  model: {
    "services": [],
    "events": [
      {
        "description": "One viewer update: a replaced Host snapshot or one run's folded view.",
        "summary": "One viewer update: a replaced Host snapshot or one run's folded view.",
        "tags": [
          {
            "name": "param",
            "argument": "frame",
            "comment": "- Host snapshot or folded run view model.",
            "text": "@param frame - Host snapshot or folded run view model.\n     *"
          },
          {
            "name": "mode",
            "comment": "emit",
            "text": "@mode emit"
          }
        ],
        "jsDoc": "/**\n * One viewer update: a replaced Host snapshot or one run's folded view.\n * @param frame - Host snapshot or folded run view model.\n * @mode emit\n */",
        "name": "kersor/event",
        "mode": "emit",
        "signature": "'kersor/event'(frame: KersorViewerFrame): void"
      }
    ],
    "objects": []
  },
}
